name: Android Build
on:
  push: 
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        
      - name: Setup Java JDK 
        uses: actions/setup-java@v2.0.0
        with:
          distribution: 'adopt'
          java-version: 8
          
      - name: Create properties file      
        uses: "finnp/create-file-action@af8500fe0b0c5d8e04934f8bb62b9dda872c5803"
        env:
            FILE_NAME: "local.properties"
            FILE_DATA: "apiKey=${{ secrets.API_KEY }}"
            
      - name: Run Ktlint
        run: ./gradlew ktlintFormat
        
      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest
      
      - name: Upload Unit Test Report
        uses: actions/upload-artifact@v2.2.3
        with:
          name: test-reports
          path: '**/build/reports/tests/'
        
      - name: Build Project
        run: ./gradlew assembleDebug
      
